
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  fields:
    service_name: nginx
  fields_under_root: true
  tail_files: true 
  tags: ["nginx", "web-tier"]


- type: log
  enabled: true
  paths:
    - /var/log/haproxy.log
  fields:
    service_name: haproxy
  fields_under_root: true
  tail_files: true
  tags: ["haproxy"]

output.logstash:
  # The Logstash hosts
  hosts: ["10.0.0.154:5044"]
